INSERT INTO [dbo].[AppManufacturers]
           ([Id]
           ,[Name]
           ,[Code]
           ,[Slug]
           ,[CoverPicture]
           ,[Visibility]
           ,[IsActive]
           ,[Country]
           ,[ExtraProperties]
           ,[ConcurrencyStamp]
           ,[CreationTime]
           ,[CreatorId])
     VALUES
           (NEWID()
           ,N'Apple'
           ,'M1'
           ,'apple'
           ,1
           ,1
           ,1
           ,'US'
           ,'test'
           ,'test'
           ,GETDATE()
           ,null)
INSERT INTO [dbo].[AppManufacturers]
           ([Id]
           ,[Name]
           ,[Code]
           ,[Slug]
           ,[CoverPicture]
           ,[Visibility]
           ,[IsActive]
           ,[Country]
           ,[ExtraProperties]
           ,[ConcurrencyStamp]
           ,[CreationTime]
           ,[CreatorId])
     VALUES
           (NEWID()
           ,N'Microsoft'
           ,'M2'
           ,'microsoft'
           ,1
           ,1
           ,1
           ,'US'
           ,'test'
           ,'test'
           ,GETDATE()
           ,null)